#cloud-config

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    discovery: %(etcd_discovery_token)s
    addr: %(client_ip)s:4001
    peer-addr: %(client_ip)s:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
ssh_authorized_keys:
  - %(rsa_public_key)s

write_files:
  - path: "/bootpxe/etcd_discovery_token"
    content: %(etcd_discovery_token)s
write_files:
  - path: "/bootpxe/rsa_public_key"
    content: %(rsa_public_key)s
write_files:
  - path: "/bootpxe/coreos-pxe.service"
    content: |
      [Unit]
      Description=CoreOSPxeAnnouncing
      After=docker.service
      Requires=docker.service

      [Service]
      TimeoutStartSec=0
      ExecStartPre=-/usr/bin/docker kill coreos-pxe
      ExecStartPre=-/usr/bin/docker rm coreos-pxe
      ExecStartPre=/usr/bin/docker pull dermatthes/coreos-pxe
      ExecStart=/usr/bin/docker run --net=host -e INTERFACE=enp8s0 -v /bootpxe/rsa_public_key:/app/rsa_public_key -v /bootpxe/etcd_discovery_token:/app/config/etcd_discovery_token --name coreos-pxe dermatthes/coreos-pxe
      ExecStop=/usr/bin/docker stop coreos-pxe


hostname: coreos-%(client_ip_dash)s
