#cloud-config

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    discovery: %(etcd_discovery_token)s
    addr: %(client_ip)s:4001
    peer-addr: %(client_ip)s:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
ssh_authorized_keys:
  - ssh-rsa %(rsa_public_key)
hostname: coreos-%(client_ip_dash)s