#!/bin/sh

set -e

pxe_server_ip=$(ifconfig $INTERFACE | grep 'inet addr:' | cut -d: -f2 | awk '{print $1}')

rsa_public_key=$(cat /app/rsa_public_key)

if [ $MODE = 'BOOTSTRAP' ]
then
    echo "BOOTSTRAP TOKEN"
    wget "https://discovery.etcd.io/new?size=3" -O /app/config/etcd_discovery_token

    echo "BOOTSTRAP-MODE: Creating new ssh key pair for inter cluster communication"
    ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
    echo "KEYGEN DONE!"
fi


echo Server IP: $pxe_server_ip

# Update discovery token, bootstrap with 3 nodes
# sed -i -e s,DISCOVERY_TOKEN,$(wget -qO- https://discovery.etcd.io/new?size=3),g /pxe/cloud-config.yml

# Fallback to default config if user dose not provide
[ ! -d /config/pxelinux.cfg ] && \
    echo "Use default configs" && cp -a /app/config/. /config

# Copy to tftp root
cp -R /config/pxelinux.cfg /app/tftp
chmod a+r /app/tftp/pxelinux.cfg/*

# Update pxelinux config to point real server ip
sed -i -e s/%\(server_ip\)s/$pxe_server_ip/ /app/tftp/pxelinux.cfg/*

echo "Starting python cloudconfig webserver (make sure to block outside requests to port 888)"
# Start http server to host cloud.config
export WORK_DIR="/app/config"
export SERVER_IP=$pxe_server_ip
export DISCOVERY_TOKEN=$(cat /app/config/etcd_discovery_token)
export PUBLIC_KEY_FILE="/app/rsa_public_key"
export INT_PRIVATE_KEY_FILE="/root/.ssh/id_rsa"
export INT_PUBLIC_KEY_FILE="/root/.ssh/id_rsa.pub"
php -d variables_order=EGPCS -S $pxe_server_ip:888 /app/httpd.php &


# Start dnsmasq as dhcp proxy to $pxe_server_ip

if [ $MODE = 'WORKERJOIN' ]
then
    ln -s /app/tftp/pxelinux.cfg/workerjoin /app/tftp/pxelinux.cfg/default
    echo "MODE SELECT: JOIN MODE!"
    dnsmasq \
        --dhcp-range=$pxe_server_ip,proxy \
        --dhcp-no-overrid \
        --dhcp-boot=pxelinux.0,pxeserver,$pxe_server_ip \
        --pxe-service=x86PC,"Join existing CoreOS Cluster",pxelinux \
        --enable-tftp \
        --tftp-root=/app/tftp \
        --user=root \
        --no-daemon
fi

if [ $MODE = 'BOOTSTRAP' ]
then
    ln -s /app/tftp/pxelinux.cfg/bootstrap /app/tftp/pxelinux.cfg/default
    echo "MODE SELECT: BOOTSTRAP MODE! (new cluster only!)"
    dnsmasq \
        --dhcp-range=$pxe_server_ip,proxy \
        --dhcp-no-overrid \
        --dhcp-boot=pxelinux.0,pxeserver,$pxe_server_ip \
        --pxe-service=x86PC,"Bootstrap CoreOS Cluster",pxelinux \
        --enable-tftp \
        --tftp-root=/app/tftp \
        --user=root \
        --no-daemon
fi

echo "ERROR: No MODE selected!"
